In [2]:
import numpy as np

#### Task 1

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Task 2

In [10]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [17]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Task 3

In [19]:
a1 = a.reshape(2, -1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
a4 = a.reshape(-1, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [24]:
a5 = a.reshape(-1, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Task 4

In [27]:
arr = np.array([1, 2, 3])
arr
arr.shape

(3,)

In [26]:
arr.T

array([1, 2, 3])

In [30]:
(arr.T).shape

(3,)

Нет. В numpy в одномерном массиве всегда одна строка.

In [32]:
np.random.random()

0.05919549685145009