In [1]:
import numpy as np

#### Task 1

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Task 2

In [3]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Task 3

In [8]:
a1 = a.reshape(2, -1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
a4 = a.reshape(-1, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a5 = a.reshape(-1, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Task 4

In [13]:
arr = np.array([1, 2, 3])
arr.shape

(3,)

In [14]:
arr.T

array([1, 2, 3])

In [15]:
(arr.T).shape

(3,)

Нет. В numpy в одномерном массиве всегда одна строка.

#### Task 5

In [16]:
arr_normal = np.random.normal(0, 1, size=(3, 4))
arr_normal

array([[-0.60010208, -0.18639724, -1.06595376,  1.88179953],
       [-0.10517707, -0.86788052, -2.37909161,  1.08924265],
       [-0.38700409, -0.61146201,  2.7858462 , -0.63087323]])

In [17]:
arr_normal.size

12

In [18]:
arr_normal_fl = arr_normal.flatten()
arr_normal_fl

array([-0.60010208, -0.18639724, -1.06595376,  1.88179953, -0.10517707,
       -0.86788052, -2.37909161,  1.08924265, -0.38700409, -0.61146201,
        2.7858462 , -0.63087323])

In [19]:
arr_normal_fl.size

12

#### Task 6

In [20]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Task 7

In [21]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [22]:
np.array_equal(a, b)

True

Отличий между массивами нет.

#### Task 8

In [23]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
v.size

10

#### Task 9

In [27]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [30]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [31]:
B.size

16

In [35]:
det_B = np.linalg.det(B)
det_B

0.0

Т.к. определитель матрицы B равен 0, то обратной матрицы для матрицы B не существует.

#### Task 10

In [39]:
rng = np.random.default_rng(seed=42)

arr1 = rng.random((2, 2))
arr1

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803]])

In [42]:
rng = np.random.default_rng(seed=42)
arr2 = rng.random((2, 2))
arr2

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803]])

In [43]:
np.array_equal(arr1, arr2)

True

#### Task 11

In [48]:
c = np.arange(16)
np.random.shuffle(x)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Task 12

In [49]:
C = c.reshape(4, -1)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
D = B + C * 10
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [52]:
np.linalg.det(D)

5.18953807259442e-26

In [54]:
np.linalg.matrix_rank(D)

2

In [55]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

#### Task 13

In [59]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [61]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])