In [1]:
import numpy as np

#### Task 1

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Task 2

In [3]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Task 3

In [8]:
a1 = a.reshape(2, -1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
a4 = a.reshape(-1, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a5 = a.reshape(-1, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Task 4

In [13]:
arr = np.array([1, 2, 3])
arr.shape

(3,)

In [14]:
arr.T

array([1, 2, 3])

In [15]:
(arr.T).shape

(3,)

Нет. В numpy в одномерном массиве всегда одна строка.

#### Task 5

In [19]:
arr_normal = np.random.normal(0, 1, size=(3, 4))
arr_normal

array([[-0.48730905,  1.47818632,  0.28822494,  0.94937202],
       [ 0.30502417, -2.80100038, -1.42404466, -1.15030179],
       [ 0.89098942, -0.88115275,  0.05620678,  0.48989751]])

In [24]:
arr_normal.size

12

In [22]:
arr_normal_fl = arr_normal.flatten()
arr_normal_fl

array([-0.48730905,  1.47818632,  0.28822494,  0.94937202,  0.30502417,
       -2.80100038, -1.42404466, -1.15030179,  0.89098942, -0.88115275,
        0.05620678,  0.48989751])

In [25]:
arr_normal_fl.size

12

#### Task 6

In [28]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Task 7

In [33]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [37]:
np.array_equal(a, b)

True

Отличий между массивами нет.

#### Task 8

In [58]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [59]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
v.size

10